export const arrProducts = [
    {
        name: 'Syltherine',
        id: '1',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        cardDescription: 'Stylish cafe chair',
        price: 2_500_000,
        oldPrice: 3_500_000,
        img: '/images/range/Syltherpng.png',
        discont: 0,
        category: 'Chair',
        new: false,
        rating: 5,
        count : 0,
        sku: 'SS001',
        tags: 'Sofa, Chair, Home, Shop',
    },
    {
        name: 'Leviosa',
        id: '2',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        cardDescription: 'Stylish cafe chair',
        price: 2_500_000,
        oldPrice: null,
        img: '/images/range/Leviosa.png',
        discont: 0,
        category: 'Chair',
        new: false,
        rating: 5,
        count : 0,
        sku: 'SS002',
        tags: 'Sofa, Chair, Home, Shop',
    },
    {
        name: 'Lolito',
        id: '3',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        cardDescription: 'Luxury big sofa',
        price: 7_000_000,
        oldPrice: 14_000_000,
        img: '/images/range/Lolito.png',
        discont: 0,
        category: 'Sofa',
        new: false,
        rating: 5,
        count : 0,
        sku: 'SS003',
        tags: 'Sofa, Chair, Home, Shop',
    },
    {
        name: 'Respira',
        id: '4',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        cardDescription: 'Outdoor bar table and stool',
        price: 500_000,
        oldPrice: null,
        img: '/images/range/Respiro.png',
        discont: 0,
        category: 'Sofa',
        new: false,
        rating: 5,
        count : 0,
        sku: 'SS004',
        tags: 'Sofa, Chair, Home, Shop',
    },
]

