export const arrProducts = [
    {
        name: 'Syltherine',
        id: '1',
        description: '',
        cardDescription: 'Stylish cafe chair',
        price: 2_500_000,
        oldPrice: 3_500_000,
        img: './images/range/Syltherpng.png',
        discont: 0,
        category: '',
        new: false,
        rating: 5,
    },
    {
        name: 'Leviosa',
        id: '2',
        description: '',
        cardDescription: 'Stylish cafe chair',
        price: 2_500_000,
        oldPrice: null,
        img: './images/range/Leviosa.png',
        discont: 0,
        category: '',
        new: false,
        rating: 5,
    },
    {
        name: 'Lolito',
        id: '3',
        description: '',
        cardDescription: 'Luxury big sofa',
        price: 7_000_000,
        oldPrice: 14_000_000,
        img: './images/range/Lolito.png',
        discont: 0,
        category: '',
        new: false,
        rating: 5,
    },
    {
        name: 'Respira',
        id: '4',
        description: '',
        cardDescription: 'Outdoor bar table and stool',
        price: 500_000,
        oldPrice: null,
        img: './images/range/Respiro.png',
        discont: 0,
        category: '',
        new: false,
        rating: 5,
    },
]

export const arrPages = [
    {
        id: 1,
        name: '1',
        img: '',
        active: true,
    },
    {
        id: 2,
        name: '2',
        img: '',
        active: false,
    },
    {
        id: 3,
        name: '3',
        img: '',
        active: false,
    },
    {
        id: 4,
        name: 'Next',
        img: '',
        active: false,
    },
]